# Generated by Django 3.0 on 2024-11-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('phonenumber', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=250, null=True)),
                ('price', models.FloatField(max_length=250, null=True)),
                ('hsncode', models.IntegerField(null=True)),
                ('gst', models.IntegerField(null=True)),
                ('cgst', models.FloatField(max_length=250, null=True)),
                ('sgst', models.FloatField(max_length=250, null=True)),
                ('discount', models.IntegerField(null=True)),
                ('stock', models.IntegerField(null=True)),
                ('barcode_number', models.CharField(max_length=250, null=True)),
                ('date', models.DateField(null=True)),
                ('purchasedstock', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250, null=True)),
                ('password', models.CharField(max_length=250, null=True)),
                ('utype', models.CharField(max_length=250, null=True)),
                ('name', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.IntegerField(null=True)),
                ('itemname', models.CharField(max_length=250, null=True)),
                ('hsncode', models.CharField(max_length=250, null=True)),
                ('price', models.CharField(max_length=250, null=True)),
                ('gst', models.IntegerField(null=True)),
                ('cgst', models.FloatField(null=True)),
                ('sgst', models.FloatField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('invoiceNo', models.CharField(max_length=250, null=True)),
                ('username', models.CharField(max_length=250, null=True)),
                ('barcode_number', models.CharField(max_length=250, null=True)),
                ('discount', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.IntegerField(null=True)),
                ('itemname', models.CharField(max_length=250, null=True)),
                ('hsncode', models.CharField(max_length=250, null=True)),
                ('price', models.CharField(max_length=250, null=True)),
                ('gst', models.IntegerField(null=True)),
                ('cgst', models.FloatField(null=True)),
                ('sgst', models.FloatField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('date', models.DateField(null=True)),
                ('invoiceNo', models.CharField(max_length=250, null=True)),
                ('username', models.CharField(max_length=250, null=True)),
                ('barcode_number', models.CharField(max_length=250, null=True)),
                ('discount', models.IntegerField(null=True)),
                ('payment_mode', models.CharField(max_length=250, null=True)),
                ('cash', models.FloatField(null=True)),
                ('UPI', models.FloatField(null=True)),
                ('status', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
